<title>my website</title>
<h1>UncleRafield's webpage</h1>
<p>A website about a roblox player, UncleRafield</p>
<img src="https://tr.rbxcdn.com/30DAY-Avatar-758CC408AD0B2A2879F2F75911D3BF45-Png/352/352/Avatar/Webp/noFilter" alt="the roblox avatar'uncleRafield'," width=200>
<h2>about me</h2>
<p>I am a roblox player that has been playing since 2017</p>
<p>although my account was made in 2023, I've had many accounts before this one</p>
<h2>My friends/badges</h2>
<p>as of me making this website, I have 20 friends</p>
<p>As of me making the website, I have over 100 badges (im to lazy to count them all)</p>
<h2>top 10 facts</h2>
<p>1)I am not an Actual Uncle (the name sounded cool)</p>
<p>2)I know how to touch grass</p>
<p>3)I am from earth</p>
<p>4) I am NOT from mars</p>
<p>5)I am a roblox player</p>
<p>6)I am ok with tech</p>
<p>7) I can't be bothered to finish the rest of the facts</p>
<h2>thanks for reading</h2>
<p>as a thanks for reading, I will do nothing.</p>
